---
kind: pipeline
type: kubernetes
name: default

resources:
  requests:
    cpu: 1000
    memory: 4000MiB

steps:
  - name: build
    image: maven:3.9.9-eclipse-temurin-21-alpine@sha256:4cbb8bf76c46b97e028998f2486ed014759a8e932480431039bdb93dffe6813e
    commands:
      - mvn package
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2

trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 519a974fca0f60f9c1bea9872694aee211a47826d93a83c37a6f8fcf5fa676be

...
