---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: prepare-tesseract
    image: franky1/tesseract:5.5.0
    commands:
      - cp --parents /usr/local/lib/libtesseract.so* /tesseract-dist/
      - ldd /usr/local/bin/tesseract | awk '{print $3}' | grep -E '^/' | xargs -I{} cp --parents {} /tesseract-dist/
      - ldd /usr/local/lib/libtesseract.so | awk '{print $3}' | grep -E '^/' | xargs -I{} cp --parents {} /tesseract-dist/
    volumes:
      - name: tesseract-dist
        path: /tesseract-dist

  - name: build
    image: maven:3.9.6-eclipse-temurin-21
    commands:
      - mkdir -p /opt/tesseract/lib
      - cp /tesseract-dist/usr/local/lib/libtesseract.so* /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/liblept.so.5 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libLerc.so.4 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libopenjp2.so.7 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libjpeg.so.62 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libpng16.so.16 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libtiff.so.6 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libwebpmux.so.3 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libwebp.so.7 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libz.so.1 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libzstd.so.1 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/liblzma.so.5 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libjbig.so.0 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libdeflate.so.0 /opt/tesseract/lib/
      - cp /tesseract-dist/lib/x86_64-linux-gnu/libgomp.so.1 /opt/tesseract/lib/

      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/opt/tesseract/lib
    volumes:
      - name: m2-cache
        path: /root/.m2/repository
      - name: tesseract-dist
        path: /tesseract-dist

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: bake-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
  - name: tesseract-dist
    temp: { }
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 68316a544820c6ae0af999b91b57e807bb54f6d63dd2a58038c0cf910bed8133

...
