---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: eclipse-temurin:21-jdk
    commands:
      - apt-get update && apt-get install -y tesseract-ocr
      - mvn package -Dtesseract.data-path=/usr/share/tessdata -Dtesseract.lib-path=/usr/lib/x86_64-linux-gnu
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 23f2c5f897be2927b497be29ba115b0fa3498d88c09efd79285732ea380eddd8

...
