---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: maven:3.9.6-eclipse-temurin-21
    commands:
      - apt-get update && apt-get install -y tesseract-ocr
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/usr/lib/x86_64-linux-gnu
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

  - name: deploy-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: deploy-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 0264c0cb7bc140f688432f9e6b1f906a8c57016d809ceddae9ed5818b8b49b30

...
