---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: maven:3.9.6-eclipse-temurin-21
    commands:
      - ./install/install-tesseract-ubuntu.sh
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/usr/lib/x86_64-linux-gnu
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: bake-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 04611b036e126044e598ba72748ca7546cfa6d43bdece09dbd2bde8794bf0f9b

...
