---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: prepare-tesseract
    image: franky1/tesseract:5.5.0
    commands:
      - mkdir -p tesseract-dist/usr/bin
      - mkdir -p tesseract-dist/usr/lib
      - cp /usr/local/bin/tesseract tesseract-dist/
      - ldd /usr/local/bin/tesseract | awk '{print $3}' | grep -E '^/' | xargs -I{} cp --parents {} tesseract-dist/
    when:
      event:
        - push

  - name: build
    image: maven:3.9.6-eclipse-temurin-21
    commands:
      - ./install/install-tesseract-ubuntu.sh
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/drone/src/tesseract-dist/usr/lib/
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: bake-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 6df1907f073f8bb5a32bb7561ba3407f8610656b625694f6335d5ee9adaffe03

...
