---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: maven:3.9.6-eclipse-temurin-21
    commands:
      - apt-get update && apt-get install -y tesseract-ocr
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/usr/lib/x86_64-linux-gnu
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: eacedb1319a7cdb59fe0945e3b2af24f980bec45f43fe7fa709fb72046fa37d5

...
