---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: prepare-tesseract
    image: franky1/tesseract:5.5.0
    commands:
      - cp /usr/local/lib/libtesseract.so* /tesseract-dist
      - ldd /usr/local/bin/tesseract | awk '{print $3}' | grep -E '^/' | xargs -I{} cp {} /tesseract-dist
      - ldd /usr/local/lib/libtesseract.so | awk '{print $3}' | grep -E '^/' | xargs -I{} cp {} /tesseract-dist
    volumes:
      - name: tesseract-dist
        path: /tesseract-dist

  - name: build
    image: maven:3.9.6-eclipse-temurin-21
    commands:
      - mkdir -p /usr/lib/x86_64-linux-gnu
      - cp -R /tesseract-dist/* /usr/lib/x86_64-linux-gnu
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/usr/lib/x86_64-linux-gnu
    volumes:
      - name: m2-cache
        path: /root/.m2/repository
      - name: tesseract-dist
        path: /tesseract-dist

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: bake-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
  - name: tesseract-dist
    temp: { }
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 7d01f12997e66c9729f2fe51459caec3b33e7fbd2e4700322059bb7c9f504404

...
