---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: maven:3.9.9-eclipse-temurin-21-alpine@sha256:4cbb8bf76c46b97e028998f2486ed014759a8e932480431039bdb93dffe6813e
    commands:
      - apk add --no-cache tesseract-ocr
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/usr/lib
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 199c46983f7051a2dcf974b33e15e7ca68cfa212846da06059196c106cd8a2ed

...
