---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: prepare-tesseract
    image: franky1/tesseract:5.5.0
    commands:
      - mkdir -p tesseract-dist/all-libs
      - cp /usr/local/lib/libtesseract.so* tesseract-dist/all-libs/
      - ldd /usr/local/bin/tesseract | awk '{print $3}' | grep -E '^/' | xargs -I{} cp {} tesseract-dist/all-libs/
    when:
      event:
        - push

  - name: build
    image: maven:3.9.6-eclipse-temurin-21
    commands:
      - ldconfig
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/drone/src/tesseract-dist/all-libs/
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: bake-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/linkedin-games-tracker
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: 297449ba74414f8625d3368937f9f410e3b2b5e5dc7ef370aa373e29ad26f478

...
