---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: maven:3.9.9-eclipse-temurin-21-alpine@sha256:4cbb8bf76c46b97e028998f2486ed014759a8e932480431039bdb93dffe6813e
    commands:
      - apk add --no-cache tesseract-ocr
      - ln -s /usr/lib/libtesseract.so.5 /usr/lib/libtesseract.so
      - mvn package -Dtesseract.data-path=/drone/src/tessdata -Dtesseract.lib-path=/usr/lib -X
    volumes:
      - name: m2-cache
        path: /root/.m2/repository

volumes:
  - name: m2-cache
    host:
      path: /var/lib/cache/.m2
trigger:
  event:
    - push
    - promote
hmac:
---
kind: signature
hmac: b771bf5a9ab6926fd3b68888c0e10e9324cf6b119b54211ef81c185107d2a494

...
